DYJetsToLL_M-4to50_HT-100to200:
  nsplit: 4
DYJetsToLL_M-4to50_HT-200to400:
  nsplit: 3
DYJetsToLL_M-4to50_HT-400to600:
  nsplit: 5
DYJetsToLL_M-4to50_HT-600toInf:
  nsplit: 6
DYJetsToLL_M-4to50_HT-70to100:
  nsplit: 3
DYJetsToLL_M-50_HT-100to200:
  nsplit: 3
DYJetsToLL_M-50_HT-1200to2500:
  nsplit: 2
DYJetsToLL_M-50_HT-200to400:
  nsplit: 4
DYJetsToLL_M-50_HT-2500toInf:
  nsplit: 2
DYJetsToLL_M-50_HT-400to600:
  nsplit: 2
DYJetsToLL_M-50_HT-600to800:
  nsplit: 2
DYJetsToLL_M-50_HT-70to100:
  nsplit: 2
DYJetsToLL_M-50_HT-800to1200:
  nsplit: 2
DYJetsToLL_inclusive_10to50:
  nsplit: 8
DYJetsToLL_inclusive_50:
  nsplit: 8
EWKWMinus2Jets_WToLNu:
  nsplit: 2
EWKWPlus2Jets_WToLNu:
  nsplit: 3
EWKZ2Jets_ZToLL:
  nsplit: 2
EWKZ2Jets_ZToNuNu:
  nsplit: 3
GluGluHToWWToLNuQQ:
  nsplit: 1
MET:
  nsplit: 30
QCD_HT1000to1500:
  nsplit: 5
QCD_HT100to200:
  nsplit: 4
QCD_HT1500to2000:
  nsplit: 3
QCD_HT2000toInf:
  nsplit: 4
QCD_HT200to300:
  nsplit: 4
QCD_HT300to500:
  nsplit: 5
QCD_HT500to700:
  nsplit: 4
QCD_HT50to100:
  nsplit: 2
QCD_HT700to1000:
  nsplit: 5
QCD_Pt-1000_MuEnriched:
  nsplit: 4
QCD_Pt-120To170_EMEnriched:
  nsplit: 2
QCD_Pt-120To170_MuEnriched:
  nsplit: 8
QCD_Pt-15To20_EMEnriched:
  nsplit: 4
QCD_Pt-15To20_MuEnriched:
  nsplit: 2
QCD_Pt-170To300_EMEnriched:
  nsplit: 1
QCD_Pt-170To300_MuEnriched:
  nsplit: 10
QCD_Pt-20To30_EMEnriched:
  nsplit: 2
QCD_Pt-20To30_MuEnriched:
  nsplit: 9
QCD_Pt-300To470_MuEnriched:
  nsplit: 7
QCD_Pt-300ToInf_EMEnriched:
  nsplit: 1
QCD_Pt-30To50_EMEnriched:
  nsplit: 3
QCD_Pt-30To50_MuEnriched:
  nsplit: 12
QCD_Pt-470To600_MuEnriched:
  nsplit: 5
QCD_Pt-50To80_EMEnriched:
  nsplit: 1
QCD_Pt-50To80_MuEnriched:
  nsplit: 5
QCD_Pt-600To800_MuEnriched:
  nsplit: 6
QCD_Pt-800To1000_MuEnriched:
  nsplit: 11
QCD_Pt-80To120_EMEnriched:
  nsplit: 2
QCD_Pt-80To120_MuEnriched:
  nsplit: 7
ST_s-channel_4f_leptonDecays:
  nsplit: 2
ST_t-channel_antitop_4f_InclusiveDecays:
  nsplit: 7
ST_t-channel_top_4f_InclusiveDecays:
  nsplit: 20
ST_tW_antitop_5f_inclusiveDecays:
  nsplit: 5
ST_tW_top_5f_inclusiveDecays:
  nsplit: 5
SingleElectron:
  nsplit: 25
SingleMuon:
  nsplit: 44
TTTo2L2Nu:
  nsplit: 8
TTToHadronic:
  nsplit: 20
TTToSemiLeptonic:
  nsplit: 30
Tau:
  nsplit: 19
VBFHToWWTo2L2Nu:
  nsplit: 3
VBFHToWWToLNuQQ:
  nsplit: 1
WJetsToLNu_HT-100To200:
  nsplit: 4
WJetsToLNu_HT-1200To2500:
  nsplit: 3
WJetsToLNu_HT-200To400:
  nsplit: 4
WJetsToLNu_HT-2500ToInf:
  nsplit: 2
WJetsToLNu_HT-400To600:
  nsplit: 5
WJetsToLNu_HT-600To800:
  nsplit: 2
WJetsToLNu_HT-800To1200:
  nsplit: 3
WJetsToLNu_inclusive:
  nsplit: 9
WW:
  nsplit: 2
WZ:
  nsplit: 2
ZZ:
  nsplit: 1